# Generated by Django 4.0.3 on 2022-04-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_attraction_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
