# Generated by Django 4.0.3 on 2022-04-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_attraction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
