# Generated by Django 4.0.3 on 2022-04-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_destination_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='photo',
            field=models.ImageField(default='', upload_to='destinations'),
        ),
    ]
