# Generated by Django 4.0.3 on 2022-04-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_destination_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='photo',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='attraction',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
