# Generated by Django 4.0.3 on 2022-04-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_attraction_photo_attraction_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
