# Generated by Django 4.0.3 on 2022-04-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_destination_state_alter_destination_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='destination',
            name='location_description',
            field=models.TextField(max_length=2000),
        ),
    ]
